// @ts-nocheck — Node-only build script (this browser project ships no @types/node).
// Offline: sweep the (a, b) chart and tabulate the LOWER bound L_R(σ) — the
// inner-hull area of the stable-norm ball — on a grid, for a few cutoffs R. The
// demo compares this (precomputed) field against the modular torus's UPPER bound
// U_{R*}(hex), recomputed live, to shade the rigorously-excluded region.
//
// Run from the repo root:
//   npx esbuild demos/stable-norm-cusp-cutoff/precompute.ts --bundle --format=esm \
//     --platform=node --alias:@/math/geometry=./src/math/geometry/index.ts \
//     --outfile=/tmp/precompute-excl.mjs && node /tmp/precompute-excl.mjs

import { writeFileSync } from 'node:fs';
import { liftToTriple } from '../_shared/markoffChart';
import { normBallArea } from '../_shared/stableNorm';
import { inFundamentalDomain } from '../_shared/markoffSymmetry';

const N = 384;          // grid resolution
const R_WIN = 3;        // (a, b) window half-width
const LOWER_RS = [2, 3, 4, 5, 10]; // cutoffs for the precomputed lower-bound fields
const OUT = 'demos/stable-norm-cusp-cutoff/lowerFieldData.ts';

const fields: Record<string, (number | null)[]> = {};
for (const R of LOWER_RS) fields[String(R)] = [];
const inDomain: number[] = [];

const start = Date.now();
for (let j = 0; j < N; j++) {
  const b = -R_WIN + (2 * R_WIN * j) / (N - 1);
  for (let i = 0; i < N; i++) {
    const a = -R_WIN + (2 * R_WIN * i) / (N - 1);
    const inside = a * a + b * b <= R_WIN * R_WIN;
    const t = inside ? liftToTriple(a, b) : null;
    // Round to 6 decimals (≥ our threshold resolution) to keep the bundle small.
    for (const R of LOWER_RS) fields[String(R)]!.push(t ? Number(normBallArea(t, R).toFixed(6)) : null);
    inDomain.push(t && inFundamentalDomain(a, b, R_WIN) ? 1 : 0);
  }
}

const payload = JSON.stringify({ n: N, rWin: R_WIN, lowerRs: LOWER_RS, fields, inDomain });
writeFileSync(
  OUT,
  '// AUTO-GENERATED by precompute.ts — do not edit by hand.\n' +
  'export interface LowerFieldData {\n' +
  '  n: number; rWin: number; lowerRs: number[];\n' +
  '  fields: Record<string, (number | null)[]>; inDomain: number[];\n' +
  '}\n' +
  `const data: LowerFieldData = ${payload};\n` +
  'export default data;\n',
);
for (const R of LOWER_RS) {
  const valid = fields[String(R)]!.filter((v): v is number => v != null);
  console.log(`R=${R}: L ∈ [${Math.min(...valid).toFixed(3)}, ${Math.max(...valid).toFixed(3)}]`);
}
console.log(`wrote ${OUT}: ${N}×${N}, ${((Date.now() - start) / 1000).toFixed(1)}s`);
