// @ts-nocheck — Node-only build script (this browser project ships no @types/node).
// Offline: tabulate the stable-norm ball volume over a LARGE window — directly at
// each point. Because V is (very nearly) mapping-class-group invariant, the result
// is essentially periodic over this window: the SL(2,ℤ) tiling of moduli space.
//
// Run from the repo root:
//   npx esbuild demos/markoff-volume-tiled/precompute.ts --bundle --format=esm \
//     --platform=node --alias:@/math/geometry=./src/math/geometry/index.ts \
//     --outfile=/tmp/precompute.mjs && node /tmp/precompute.mjs

import { writeFileSync } from 'node:fs';
import { liftToTriple } from '../_shared/markoffChart';
import { normBallArea } from '../_shared/stableNorm';

const N = 640;       // grid resolution
const R_WIN = 18;    // (a, b) window half-width — many SL(2,ℤ) cells across
const NORM_R = 48;   // slope cutoff — large enough to stay exact this far out
const OUT = 'demos/markoff-volume-tiled/volumeData.ts';

const values: (number | null)[] = [];
const start = Date.now();
for (let j = 0; j < N; j++) {
  const b = -R_WIN + (2 * R_WIN * j) / (N - 1);
  for (let i = 0; i < N; i++) {
    const a = -R_WIN + (2 * R_WIN * i) / (N - 1);
    if (a * a + b * b > R_WIN * R_WIN) { values.push(null); continue; }
    const t = liftToTriple(a, b);
    if (!t) { values.push(null); continue; }
    const v = normBallArea(t, NORM_R);
    values.push(Number.isFinite(v) ? v : null);
  }
}

const payload = JSON.stringify({ n: N, rWin: R_WIN, normR: NORM_R, values });
writeFileSync(
  OUT,
  '// AUTO-GENERATED by precompute.ts — do not edit by hand.\n' +
  'export interface VolumeData { n: number; rWin: number; normR: number; values: (number | null)[]; }\n' +
  `const data: VolumeData = ${payload};\n` +
  'export default data;\n',
);
let lo = Infinity, hi = -Infinity, count = 0;
for (const v of values) { if (v == null) continue; count++; if (v < lo) lo = v; if (v > hi) hi = v; }
console.log(
  `wrote ${OUT}: ${N}×${N}, ${count} valid, ` +
  `V ∈ [${lo.toFixed(3)}, ${hi.toFixed(3)}], ${((Date.now() - start) / 1000).toFixed(1)}s`,
);
