// @ts-nocheck — Node-only build script (this browser project ships no @types/node).
// Offline: sweep the (a, b) chart and tabulate the stable-norm ball volume on a
// grid, so the demo loads a ready surface + contours instead of recomputing
// hundreds of curves per vertex at runtime.
//
// Run from the repo root:
//   npx esbuild demos/_shared/volumeData.precompute.ts --bundle --format=esm \
//     --platform=node --alias:@/math/geometry=./src/math/geometry/index.ts \
//     --outfile=/tmp/precompute.mjs && node /tmp/precompute.mjs

import { writeFileSync } from 'node:fs';
import { liftToTriple } from '../_shared/markoffChart';
import { normBallArea } from '../_shared/stableNorm';

const N = 256;       // grid resolution
const R_WIN = 3;     // (a, b) window half-width
const NORM_R = 80;   // slope cutoff for the inner-estimate ball (converged well before this)
const OUT = 'demos/_shared/volumeData.ts';

const values: (number | null)[] = [];
const start = Date.now();
for (let j = 0; j < N; j++) {
  const b = -R_WIN + (2 * R_WIN * j) / (N - 1);
  for (let i = 0; i < N; i++) {
    const a = -R_WIN + (2 * R_WIN * i) / (N - 1);
    if (a * a + b * b > R_WIN * R_WIN) { values.push(null); continue; }
    const t = liftToTriple(a, b);
    values.push(t ? normBallArea(t, NORM_R) : null);
  }
}

const payload = JSON.stringify({ n: N, rWin: R_WIN, normR: NORM_R, values });
writeFileSync(
  OUT,
  '// AUTO-GENERATED by precompute.ts — do not edit by hand.\n' +
  'export interface VolumeData { n: number; rWin: number; normR: number; values: (number | null)[]; }\n' +
  `const data: VolumeData = ${payload};\n` +
  'export default data;\n',
);
const valid = values.filter((v): v is number => v != null);
console.log(
  `wrote ${OUT}: ${N}×${N}, ${valid.length} valid, ` +
  `V ∈ [${Math.min(...valid).toFixed(3)}, ${Math.max(...valid).toFixed(3)}], ` +
  `${((Date.now() - start) / 1000).toFixed(1)}s`,
);
